---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000    #preciser l'id du user qui sera utilisé par qbittorrent
      - PGID=1000    #preciser l'id du group du user qui sera utilisé par qbittorrent
      - TZ=Etc/UTC
      #- WEBUI_PORT=8080  ne pas utiliser si on utilise un reverse proxy
    volumes:
      - /path/to/appdata/config:/config
      - /path/to/downloads:/downloads
    ports:
      #- 8080:8080      ne pas utiliser si on utilise un reverse proxy
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
